# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 376)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(220, 310, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.line1 = QtWidgets.QLineEdit(Form)
        self.line1.setGeometry(QtCore.QRect(10, 50, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line1.setFont(font)
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(Form)
        self.line2.setGeometry(QtCore.QRect(10, 90, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line2.setFont(font)
        self.line2.setObjectName("line2")
        self.line4 = QtWidgets.QLineEdit(Form)
        self.line4.setGeometry(QtCore.QRect(10, 170, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line4.setFont(font)
        self.line4.setObjectName("line4")
        self.line5 = QtWidgets.QLineEdit(Form)
        self.line5.setGeometry(QtCore.QRect(10, 210, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line5.setFont(font)
        self.line5.setObjectName("line5")
        self.line7 = QtWidgets.QLineEdit(Form)
        self.line7.setGeometry(QtCore.QRect(10, 290, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line7.setFont(font)
        self.line7.setObjectName("line7")
        self.line6 = QtWidgets.QLineEdit(Form)
        self.line6.setGeometry(QtCore.QRect(10, 250, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line6.setFont(font)
        self.line6.setObjectName("line6")
        self.line3 = QtWidgets.QLineEdit(Form)
        self.line3.setGeometry(QtCore.QRect(10, 130, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line3.setFont(font)
        self.line3.setObjectName("line3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ДОБАВИТЬ ИЛИ ИЗМЕНИТЬ ДАННЫЕ"))
        self.button.setText(_translate("Form", "Добавить запись"))
        self.line1.setPlaceholderText(_translate("Form", "ID"))
        self.line2.setPlaceholderText(_translate("Form", "сорт"))
        self.line4.setPlaceholderText(_translate("Form", "молотый/в зернах"))
        self.line5.setPlaceholderText(_translate("Form", "вкус"))
        self.line7.setPlaceholderText(_translate("Form", "объем"))
        self.line6.setPlaceholderText(_translate("Form", "цена"))
        self.line3.setPlaceholderText(_translate("Form", "обжарка"))
