# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(855, 480)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(0, 51, 861, 431))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.button_main = QtWidgets.QPushButton(Form)
        self.button_main.setGeometry(QtCore.QRect(650, 10, 201, 41))
        self.button_main.setObjectName("button_main")
        self.download = QtWidgets.QPushButton(Form)
        self.download.setGeometry(QtCore.QRect(0, 10, 201, 41))
        self.download.setObjectName("download")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_main.setText(_translate("Form", "Режим редактирования"))
        self.download.setText(_translate("Form", "Загрузить изменения"))
